# TensorFlow Workflow

after: https://www.tensorflow.org/versions/r0.12/get_started/index.html

_Just to get a feeling for the basic code layout_ ...

In [1]:
import tensorflow as tf
import numpy as np

Create a dataset that is perfect for linear regression ;-)

In [2]:
# X has 20 rows and 2 columns
X_data = np.random.uniform(-10,10,(20,2))
X_data[:,1] = X_data[:,1] * 20 + 2
print(X_data.shape)
X_data

(20, 2)


array([[  -8.48161753,  130.8951781 ],
       [   0.50835075,  -13.61598963],
       [  -6.46817309,  201.71351079],
       [  -5.17307403,   95.73240636],
       [   2.00536176,  148.24350239],
       [   7.28274494, -100.07691831],
       [   0.29564526, -171.71378107],
       [   1.04667081,  136.95461982],
       [   9.84277125, -189.79676808],
       [   4.37656755,   59.06528433],
       [  -9.10891275, -156.68919186],
       [  -4.18878571,    5.15639683],
       [   6.1150586 ,  -59.72335723],
       [   8.70997612,  108.72768169],
       [   2.12385014,  119.9721742 ],
       [  -2.46033943,   93.87671407],
       [   2.67011729, -192.73406057],
       [   1.12070497,  112.03367351],
       [   3.32822061,   55.35965048],
       [  -8.25540679,  151.96840659]])

In [4]:
# Our y happens to be perfectly correlated...
y_data = 30 + 3 * X_data[:,0] - X_data[:,1]
print(y_data.shape)
y_data

(20,)


array([-126.3400307 ,   45.14104188, -191.11803007,  -81.25162846,
       -112.2274171 ,  151.92515314,  202.60071684, -103.8146074 ,
        249.32508184,  -15.93558169,  159.3624536 ,   12.27724603,
        108.06853304,  -52.59775334,  -83.60062379,  -71.25773236,
        230.74441245,  -78.6715586 ,  -15.37498864, -146.73462695])

#### First, define the whole computational graph.

Declare placeholders for the data:

In [5]:
X = tf.placeholder(tf.float64, [None, 2])
y = tf.placeholder(tf.float64, [None])
X, y

(<tf.Tensor 'Placeholder:0' shape=(?, 2) dtype=float64>,
 <tf.Tensor 'Placeholder_1:0' shape=(?,) dtype=float64>)

Declare a weight vector and the bias, a scalar:

In [6]:
# the weights will be randomly initialized to small values
W = tf.Variable(tf.truncated_normal([2,1], stddev=1,dtype='float64'))
b = tf.Variable(tf.zeros([1.0], dtype='float64'))
W.get_shape(), b.get_shape()

(TensorShape([Dimension(2), Dimension(1)]), TensorShape([Dimension(1)]))

If we now tried to evaluate W, we'd get an error, as we don't have created a Session yet:

In [7]:
W.eval()

ValueError: Cannot evaluate tensor using `eval()`: No default session is registered. Use `with sess.as_default()` or pass an explicit session to `eval(session=sess)`

We need to define the equation for predicting y from X:

In [8]:
# Construct a linear model
y_hat = tf.add(tf.matmul(X, W), b)
y_hat

<tf.Tensor 'Add:0' shape=(?, 1) dtype=float64>

Now, we need to define our loss function, choosing MSE.

In [9]:
loss = tf.reduce_mean(tf.square(y - tf.squeeze(y_hat)))
loss

<tf.Tensor 'Mean:0' shape=<unknown> dtype=float64>

We need to choose an optimization method and a learning rate:

In [10]:
#optimizer = tf.train.GradientDescentOptimizer(1e-5)
optimizer = tf.train.AdamOptimizer(1e-2)
train = optimizer.minimize(loss)

Lastly, before executing the computation, define a graph node to initialize the variables:

In [11]:
init = tf.initialize_all_variables()

#### Now we can run the computation:

First, create a TensorFlow Session to execute the graph:

In [12]:
sess = tf.Session()
sess.run(init)

Let's have a look at the initialized weights vector and the bias:

In [13]:
W.eval(sess)

array([[-1.21915686],
       [ 0.60754226]])

In [14]:
b.eval(sess)

array([ 0.])

Now, train the model:

In [ ]:
for i in range(10000):
#for i in range(100000):
    sess.run(train, feed_dict={X:X_data, y:y_data})
    if i % 1000 == 0:
    #if i % 1000 == 0:    
        print('Step {}: W = {}, b = {}, loss = {}'.format(i,
                sess.run(W), sess.run(b), sess.run(loss, feed_dict={X:X_data, y:y_data})))
